### ISSUE TITLE
Broken pipe

### ISSUE THREAD

**Issue by duramato** [areeb-beigh/RSS2IRC#3]
When using many rss sources it seems it can't coup with that, and and throws a `Broken pipe` when connecting to the irc channel/idenitfing. I tried adding sleep()s but didn't worked .
The traceback is bellow:

```
Traceback (most recent call last):
  File "rss2irc.py", line 138, in <module>
    update()
  File "rss2irc.py", line 136, in update
    feed_refresh()
  File "rss2irc.py", line 93, in feed_refresh
    msg(defaultChannel, m)
  File "rss2irc.py", line 65, in msg
    s.send('PRIVMSG '+str(defaultChannel)+' :'+str(msg)+'\r\n')
socket.error: [Errno 32] Broken pipe
```

**Comment by areebbeigh** [comment]
Thank you for reporting the problem duramato, could you also include the RSS sources you put in the script please? I will try to fix it as soon as possible.

**Comment by duramato** [comment]
I have 10 rss sources, some are private ones i would rather not share. Try maybe reproduce with 10 rss feeds you know, if that doesn't work i can share you the sources privatly if its ok to you

**Comment by areebbeigh** [comment]
Alright, I will start working on the problem soon, hopefully in a wk or two. Busy with exams.

**Comment by areebbeigh** [comment]
Hi, I couldn't reproduce this issue on v2.1 (or before) with multiple feed sources, I think what might have caused that broken pipe was a ping timeout on the IRC server.

**Comment by duramato** [comment]
Which IRC network did you try? It happens to me on freenode

**Comment by areebbeigh** [comment]
I tried it on freenode as well.

**Comment by duramato** [comment]
Mm I'll have to try the new version. I don't know the base code but can't exception be catched and retry the connection? 
Also forgot to mention Im running this in an upstart script with the respaw command

**Comment by duramato** [comment]
Mm I'll have to try the new version. I don't know the base code but can't exception be catched and retry the connection? 
Also forgot to mention Im running this in an upstart script with the respaw command
