### ISSUE TITLE
Can't connect to Recycled

### ISSUE THREAD

**Issue by Kcchouette** [areeb-beigh/RSS2IRC#7]
```
$ python3 rss2irc.py 

    ---------------------------------------------
    RSS2IRC Bot by Areeb - github.com/areebbeigh
    ---------------------------------------------
    
Attempting to identify...
b'PRIVMSG NickServ :IDENTIFY RSS r\r\n'
b'PRIVMSG NickServ :IDENTIFY r\r\n'

[':Moldy.recycled-irc.net', 'NOTICE', 'AUTH', ':***', 'Looking', 'up', 'your', 'hostname...']
[':Moldy.recycled-irc.net', 'NOTICE', 'AUTH', ':***', 'Checking', 'ident...']
[':Moldy.recycled-irc.net', 'NOTICE', 'AUTH', ':***', "Couldn't", 'resolve', 'your', 'hostname;', 'using', 'your', 'IP', 'address', 'instead']
[':Moldy.recycled-irc.net', 'NOTICE', 'AUTH', ':***', 'No', 'ident', 'response;', 'username', 'prefixed', 'with', '~']
['PING', ':C844221B']
Responded to PING
[':Moldy.recycled-irc.net', '451', 'PRIVMSG', ':You', 'have', 'not', 'registered']
[':Moldy.recycled-irc.net', '451', 'PRIVMSG', ':You', 'have', 'not', 'registered']
[':Moldy.recycled-irc.net', '451', 'JOIN', ':You', 'have', 'not', 'registered']
[':Moldy.recycled-irc.net', '451', 'PRIVMSG', ':You', 'have', 'not', 'registered']

[':Moldy.recycled-irc.net', '451', 'PRIVMSG', ':You', 'have', 'not', 'registered']
:Moldy.recycled-irc.net 005 RSS STATUSMSG=@%+ EXCEPTS INVEX :are supported by 
[':Moldy.recycled-irc.net', '001', 'RSS', ':Welcome', 'to', 'the', 'Recycled', 'IRC', 'IRC', 'Network', 'RSS!~RSS@163.172.148.98']
[':Moldy.recycled-irc.net', '002', 'RSS', ':Your', 'host', 'is', 'Moldy.recycled-irc.net,', 'running', 'version', 'Unreal3.2.10.2']
[':Moldy.recycled-irc.net', '003', 'RSS', ':This', 'server', 'was', 'created', 'Thu', 'May', '22', '2014', 'at', '12:22:27', 'CEST']
[':Moldy.recycled-irc.net', '004', 'RSS', 'Moldy.recycled-irc.net', 'Unreal3.2.10.2', 'iowghraAsORTVSxNCWqBzvdHtGpI', 'lvhopsmntikrRcaqOALQbSeIKVfMCuzNTGjZ']
[':Moldy.recycled-irc.net', '005', 'RSS', 'CMDS=KNOCK,MAP,DCCALLOW,USERIP,STARTTLS', 'UHNAMES', 'NAMESX', 'SAFELIST', 'HCN', 'MAXCHANNELS=50', 'CHANLIMIT=#:50', 'MAXLIST=b:80,e:80,I:80', 'NICKLEN=30', 'CHANNELLEN=32', 'TOPICLEN=307', 'KICKLEN=307', 'AWAYLEN=307', ':are', 'supported', 'by', 'this', 'server']
[':Moldy.recycled-irc.net', '005', 'RSS', 'MAXTARGETS=20', 'WALLCHOPS', 'WATCH=128', 'WATCHOPTS=A', 'SILENCE=15', 'MODES=12', 'CHANTYPES=#', 'PREFIX=(ohv)@%+', 'CHANMODES=beIqa,kfL,lj,psmntirRcOAQKVCuzNSMTGZ', 'NETWORK=Recycled-IRC', 'CASEMAPPING=ascii', 'EXTBAN=~,qjncrRa', 'ELIST=MNUCT', ':are', 'supported', 'by', 'this', 'server']
:Moldy.recycled-irc.net 372 RSS :-                 
['this', 'server']
[':Moldy.recycled-irc.net', '251', 'RSS', ':There', 'are', '141', 'users', 'and', '593', 'invisible', 'on', '2', 'servers']
[':Moldy.recycled-irc.net', '252', 'RSS', '11', ':operator(s)', 'online']
[':Moldy.recycled-irc.net', '253', 'RSS', '1', ':unknown', 'connection(s)']
[':Moldy.recycled-irc.net', '254', 'RSS', '225', ':channels', 'formed']
[':Moldy.recycled-irc.net', '255', 'RSS', ':I', 'have', '592', 'clients', 'and', '0', 'servers']
[':Moldy.recycled-irc.net', '265', 'RSS', '592', '654', ':Current', 'local', 'users', '592,', 'max', '654']
[':Moldy.recycled-irc.net', '266', 'RSS', '734', '7576', ':Current', 'global', 'users', '734,', 'max', '7576']
[':Moldy.recycled-irc.net', '375', 'RSS', ':-', 'Moldy.recycled-irc.net', 'Message', 'of', 'the', 'Day', '-']
[':Moldy.recycled-irc.net', '372', 'RSS', ':-', '9/4/2013', '20:35']
[':Moldy.recycled-irc.net', '372', 'RSS', ':-', '..,;++HHHH+H+;;,.']
[':Moldy.recycled-irc.net', '372', 'RSS', ':-', ',;+HHMMMMMMMMMMMMHH+;.']
[':Moldy.recycled-irc.net', '372', 'RSS', ':-', '.;+MMMMMMMMMMMMMMMMMMMMMH;,']
[':Moldy.recycled-irc.net', '372', 'RSS', ':-', '.+HHMMMMMMMMMMMMH#MMMMMMMMMMH;']
:
['.;HMMMMMMMMMMMMMMH', '+HMMMMMMMMMMMH,']
[':Moldy.recycled-irc.net', '372', 'RSS', ':-', ',+MMMMMMMMMMMMMMMMH', '+MMMMMMMMMMMH;']
[':Moldy.recycled-irc.net', '372', 'RSS', ':-', ';MMMMMMMMMMMMMMM#MMH', '+MMMMMMMMMMM+.']
[':Moldy.recycled-irc.net', '372', 'RSS', ':-', '+HMMMMMMMMMMMMMMM##MH', ';HMMMMMMMMMM+.']
[':Moldy.recycled-irc.net', '372', 'RSS', ':-', '.+MMMMMMMMMMMMMMMMMMMMH', ';HMMMMMMMMMM+,']
[':Moldy.recycled-irc.net', '372', 'RSS', ':-', '.+MMMMMMMMMMMMMMMMMMMMMH', ';HMMMMMMMMMM+,']
[':Moldy.recycled-irc.net', '372', 'RSS', ':-', '.+MMMMMMMMMMMMMMMMMMMMMH', ';HMMMMMMMMMM+,']
[':Moldy.recycled-irc.net', '372', 'RSS', ':-', '.+MMMMMMMMMMMMMMMMMMMMMMH', ';HMMMMMMMMMM;']
[':Moldy.recycled-irc.net', '372', 'RSS', ':-', '+MMMMMMMMMMMMMMMMMHHH+++;', ';HMMMMMMMMMH']
[':Moldy.recycled-irc.net', '372', 'RSS', ':-', ';MMMMMMMMMMMMMMMH+;', ';HMMMMMMMMM+']
[':Moldy.recycled-irc.net', '372', 'RSS', ':-', ',HMMMMMMMMMMMMMH+', ';MMMMMMMMMH']
:Moldy.recycled-irc.net 372 RSS :-         .+
['Moldy.recycled-irc.net', '372', 'RSS', ':-', '.HMMMMMMMMMMMMH+', '+MMMMMMMMM+']
[':Moldy.recycled-irc.net', '372', 'RSS', ':-', ';MMMMMMMMMMMM+', 'HMMMMMMMMH']
[':Moldy.recycled-irc.net', '372', 'RSS', ':-', ',HMMMMMMMMMMH;', ';MMMMMMMMM+']
[':Moldy.recycled-irc.net', '372', 'RSS', ':-', '+MMMMMMMMMMH;', 'HMMMMMMMMH']
[':Moldy.recycled-irc.net', '372', 'RSS', ':-', ',HMMMMMMMMM+', ';MMMMMMMMM']
[':Moldy.recycled-irc.net', '372', 'RSS', ':-', '.;MMMMMMMMM+', 'HMMMMMMMM+']
[':Moldy.recycled-irc.net', '372', 'RSS', ':-', ',HMMMMMMMM+', ';HMMMMMMMMH']
[':Moldy.recycled-irc.net', '372', 'RSS', ':-', ';MMMMMMMMH', 'Recycled-IRC', '+MMMMMMMMMH']
Traceback (most recent call last):
  File "rss2irc.py", line 314, in <module>
    main()
  File "rss2irc.py", line 58, in main
    irc.connect()
  File "rss2irc.py", line 81, in connect
    read_buffer = "" + self.s.recv(1024).decode("UTF-8")
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe9 in position 118: invalid continuation byte
```

IRC server is `irc.recycled-irc.net`, port `6667`, the nickname is not registred

**Comment by areebbeigh** [comment]
Thanks for the report. It was because of the Latin text. Fixed now.

**Comment by Kcchouette** [comment]
@areebbeigh seems to be not fixed:

```
...
[':Moldy.recycled-irc.net', '372', 'RSS', ':-']
[':Moldy.recycled-irc.net', '372', 'RSS', ':-', '___']
:Moldy.recycled-irc.net 372 RS
Traceback (most recent call last):
  File "rss2irc.py", line 322, in <module>
    main()
  File "rss2irc.py", line 58, in main
    irc.connect()
  File "rss2irc.py", line 97, in connect
    print(line)
UnicodeEncodeError: 'ascii' codec can't encode character '\xe0' in position 95: ordinal not in range(128)
```

**Comment by Kcchouette** [comment]
see with @areebbeigh, it's because ubuntu default docker file does not have good locale.
Now using https://github.com/Kcchouette/docker-ubuntu/ for building my ubuntu
